CREATE TABLE HSOL_RegPrevEduPace
(
	RegID VARCHAR(2) NOT NULL CONSTRAINT DF_HSOL_RegPrevEduPace_RegID DEFAULT(''),
	PaceTypeID VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_RegPrevEduPace_PaceTypeID DEFAULT(''),
	LevelID VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_RegPrevEduPace_LevelID DEFAULT(''),

	CONSTRAINT PK_HSOL_RegPrevEduPace_RegID PRIMARY KEY CLUSTERED (RegID)
)
