CREATE TABLE HSOL_RegFamily
(
	RegID VARCHAR(13) NOT NULL CONSTRAINT DF_HSOL_RegFamily_RegID DEFAULT(''),
	EmergencyPhone VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_RegFamily_EmergencyPhone DEFAULT(''),
	MaritalStatus INT NOT NULL CONSTRAINT DF_HSOL_RegFamily_MaritalStatus DEFAULT(0),

	CONSTRAINT PK_HSOL_RegFamily_RegID PRIMARY KEY CLUSTERED (RegID)
)
