CREATE TABLE HSOL_RegFamilySibline
(
	RegID VARCHAR(13) NOT NULL CONSTRAINT DF_HSOL_RegFamilySibline_RegID DEFAULT(''),
	PersonName VARCHAR(30) NOT NULL CONSTRAINT DF_HSOL_RegFamilySibline_PersonName DEFAULT(''),
	Age INT NOT NULL CONSTRAINT DF_HSOL_RegFamilySibline_Age DEFAULT(0),
	ReasonNotApply VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_RegFamilySibline_ReasonNotApply DEFAULT(''),

	CONSTRAINT PK_HSOL_RegFamilySibline_RegID PRIMARY KEY CLUSTERED (RegID)
)
