CREATE TABLE HSOL_Person
(
	PersonID VARCHAR(12) NOT NULL CONSTRAINT DF_HSOL_Person_PersonID DEFAULT(''),
	PersonName VARCHAR(40) NOT NULL CONSTRAINT DF_HSOL_Person_PersonName DEFAULT(''),
	NickName VARCHAR(15) NOT NULl CONSTRAINT DF_HSOL_Person_NickName DEFAULT(''),

	BirthDate DATETIME NOT NULL CONSTRAINT DF_HSOL_Person_TglLahir DEFAULT('1900-01-01'),
	BirthPlace VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_Person_TempatLahir DEFAULT(''),
	Gender BIT NOT NULL CONSTRAINT DF_HSOL_Person_Gender DEFAULT(0),

	FullAddr VARCHAR(255) NOT NULL CONSTRAINT DF_HSOL_Person_FullAddr  DEFAULT(''),
	ShortAddr VARCHAR(30) NOT NULL CONSTRAINT DF_HSOL_Person_ShortAddr DEFAULT(''),
	City VARCHAR(30) NOT NULL CONSTRAINT DF_HSOL_Person_City DEFAULT(''),

	PhoneNo VARCHAR(30) NOT NULL CONSTRAINT DF_HSOL_Person_PhoneNo DEFAULT(''),
	Email VARCHAR(60) NOT NULL CONSTRAINT DF_HSOL_Person_Email DEFAULT(''),

	CONSTRAINT PK_HSOL_Person_PersonID PRIMARY KEY CLUSTERED (PersonID)
)
