CREATE TABLE HSOL_Grade
(
	GradeID VARCHAR(3) NOT NULL CONSTRAINT DF_HSOL_Grade_GradeID DEFAULT(''),
	GradeName VARCHAR(30) NOT NULL CONSTRAINT DF_HSOL_Grade_GradeName DEFAULT(''),

	CONSTRAINT PK_HSOL_Grade_GradeID PRIMARY KEY CLUSTERED (GradeID)
)
