CREATE TABLE HSOL_RegPrevEdu
(
	RegID VARCHAR(2) NOT NULL CONSTRAINT DF_HSOL_RegPrevEdu_RegID DEFAULT(''),
	PrevEduName VARCHAR(50) NOT NULL CONSTRAINT DF_HSOL_RegPrevEdu_PrevEduName DEFAULT(''),
	PrevEduType INT NOT NULL CONSTRAINT DF_HSOL_RegPrevEdu_PrevEduType DEFAULT(''),
	YearAttended VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_RegPrevEdu_YearAttended DEFAULT(''),
	HighestGrade VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_RegPrevEdu_HighestGrade DEFAULT(''),
	IsAce VARCHAR(20) NOT NULL CONSTRAINT DF_HSOL_RegPrevEdu_IsAce DEFAULT(''),


	CONSTRAINT PK_HSOL_RegPrevEdu_RegID PRIMARY KEY CLUSTERED (RegID)
)
