CREATE TABLE HSOL_ParamNo
(
	ParamID VARCHAR(5) NOT NULL CONSTRAINT DF_HSOL_ParamNo_ParamID DEFAULT(''),
	ParamValue VARCHAR(5) NOT NULL CONSTRAINT DF_HSOL_ParamNo_ParamValue DEFAULT(''),

	CONSTRAINT PK_HSOL_ParamNo_ParamID PRIMARY KEY CLUSTERED (ParamID)
)
